import type { Metadata } from 'next'
import './globals.css'
import { cn } from '../lib/utils'
import { fontMelodrama, fontPencerio, fontSupreme } from '../lib/fonts'
import { LenisProvider } from '@/hooks/use-smooth-scroll'
import Cursor from '@/components/ui/cursor'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'antialiased bg-a-black scroll-auto',
          fontMelodrama.variable,
          fontPencerio.variable,
          fontSupreme.variable
        )}
      >
        <LenisProvider>{children}</LenisProvider>
        <Cursor />
      </body>
    </html>
  )
}
