import type { Metadata } from 'next'
import './globals.css'
import { cn } from '../lib/utils'
import { fontMelodrama, fontPencerio, fontSupreme } from '../lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'antialiased',
          fontMelodrama.variable,
          fontPencerio.variable,
          fontSupreme.variable
        )}
      >
        {children}
      </body>
    </html>
  )
}
